### ISSUE TITLE
how to test when your script fails

### ISSUE THREAD

**Issue by albfan** [mlafeldt/sharness#18]
I'm stuck with this test

https://github.com/albfan/bash-ini-parser/commit/1be6551065c14b4055902888eaa06ba3c6ba0408

Go to test dir.

    $ cd t

Funnily

    $ bash t0002-invalid.sh

passes correctly, but fails executed through

    $ make

The related function fail and is trapped by [sharness.sh#L160](https://github.com/mlafeldt/sharness/blob/master/sharness.sh#L160)

don't know if I have to modify Makefile, test file,  or script itself.

**Comment by chriscool** [comment]
Could you try running `make SHELL_PATH=/bin/bash`?

**Comment by chriscool** [comment]
You can also change `#!/bin/sh` at the top of the script to `#!/bin/bash` and run `./t0002-invalid.sh` to see if it's a problem with /bin/sh not being bash.
By the way what  is the output of `ls -l /bin/sh`?

**Comment by albfan** [comment]
Ouch!

I will check as soon as possible, but I bet that's the problem.

Let's see

**Comment by albfan** [comment]
As `SHELL_PATH` is [only used on Makefile](https://github.com/albfan/bash-ini-parser/blob/1be6551065c14b4055902888eaa06ba3c6ba0408/t/Makefile#L37
), changing inside test case doesn't work

Issuing

    $ make SHELL_PATH=/bin/bash

works perfect, because although

    $ ls -l /bin/sh
    lrwxrwxrwx 1 root root 4 dic 30 23:08 /bin/sh -> bash

[bash doc](http://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html) says

>Invoked with name sh

>If Bash is invoked with the name sh, it tries to mimic the startup behavior of historical versions of sh as closely as possible, while conforming to the POSIX standard as well.

Thanks
