### ISSUE TITLE
Including test_pause()

### ISSUE THREAD

**Issue by chriscool** [mlafeldt/sharness#19]
Git has a test_pause() function that can be used to debug sharness tests:

https://github.com/git/git/blob/master/t/test-lib-functions.sh#L140

The README.git file also talks about it:

https://github.com/mlafeldt/sharness/blob/master/README.git#L578

I think it would be nice if it could be added to sharness.

Would a patch to add it be accepted?

**Comment by mlafeldt** [comment]
Yeah, of course. Just send me a pull request.

**Comment by chriscool** [comment]
As I merged my PR, this can be closed.
