### ISSUE TITLE
Some documentation about contributing to sharness

### ISSUE THREAD

**Issue by chriscool** [mlafeldt/sharness#31]
I think we should have a CONTRIBUTING.md document to tell things like:

- the same coding rules as in git.git should be followed (https://github.com/git/git/blob/master/Documentation/CodingGuidelines)
- if some similar changes can benefit Git it is a good idea to first send patchs to the Git mailing list (https://github.com/git/git/blob/master/Documentation/SubmittingPatches)
- the code in sharness.sh should be kept as much as possible similar as git/git/t/test-lib.sh (variable names, function names, ...)
- if some changes do not depend on each other, it is better to send different PRs with as few changes as possible in each PR, rather than a big PR with everything
- it is better to have tests with each PR, as sharness has its own test suite
- API.md should be updated using `make doc` when new functions are added

Other things, thoughts?

**Comment by mlafeldt** [comment]
Very good idea!

**Comment by chriscool** [comment]
Ok thanks, I will take a look at doing that.

**Comment by chriscool** [comment]
Closing as it has been addressed by PR #32 and #34.
