### ISSUE TITLE
Sharnessify script

### ISSUE THREAD

**Issue by chriscool** [mlafeldt/sharness#38]
I created this repo:

https://github.com/chriscool/sharnessify

It has a script to easily add Sharness infrastructure to some projects.

People working on IPFS related repos needed a simple way to add Sharness infrastructure to those repos.

Maybe we could talk about it somewhere in the documentation?

**Comment by mlafeldt** [comment]
I suggest adding it to https://github.com/mlafeldt/sharness#per-project-installation

**Comment by chriscool** [comment]
Let's close this, as PR #39 is merged.
